[2022-07-16 19:37:39,686] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.upload_to_pg manual__2022-07-16T19:37:23.025403+00:00 [queued]>
[2022-07-16 19:37:39,695] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.upload_to_pg manual__2022-07-16T19:37:23.025403+00:00 [queued]>
[2022-07-16 19:37:39,695] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 19:37:39,695] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-16 19:37:39,695] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 19:37:39,708] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): upload_to_pg> on 2022-07-16 19:37:23.025403+00:00
[2022-07-16 19:37:39,714] {standard_task_runner.py:52} INFO - Started process 3093 to run task
[2022-07-16 19:37:39,716] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'upload_to_pg', 'manual__2022-07-16T19:37:23.025403+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpzqfcwm2n', '--error-file', '/tmp/tmp43vjgj_5']
[2022-07-16 19:37:39,717] {standard_task_runner.py:80} INFO - Job 24: Subtask upload_to_pg
[2022-07-16 19:37:39,764] {task_command.py:371} INFO - Running <TaskInstance: process_files.upload_to_pg manual__2022-07-16T19:37:23.025403+00:00 [running]> on host 98d7be6daedb
[2022-07-16 19:37:39,790] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1471, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1575, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2232, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1188, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 347, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 384, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: files/create_world.sql
[2022-07-16 19:37:39,797] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=process_files, task_id=upload_to_pg, execution_date=20220716T193723, start_date=20220716T193739, end_date=20220716T193739
[2022-07-16 19:37:39,805] {standard_task_runner.py:97} ERROR - Failed to execute job 24 for task upload_to_pg (files/create_world.sql; 3093)
[2022-07-16 19:37:39,847] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 19:37:39,882] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
