[2022-07-16 19:12:51,985] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.setup_http_conn manual__2022-07-16T19:05:47.374925+00:00 [queued]>
[2022-07-16 19:12:51,993] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: process_files.setup_http_conn manual__2022-07-16T19:05:47.374925+00:00 [queued]>
[2022-07-16 19:12:51,993] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 19:12:51,993] {taskinstance.py:1377} INFO - Starting attempt 3 of 3
[2022-07-16 19:12:51,993] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 19:12:52,006] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): setup_http_conn> on 2022-07-16 19:05:47.374925+00:00
[2022-07-16 19:12:52,013] {standard_task_runner.py:52} INFO - Started process 1474 to run task
[2022-07-16 19:12:52,015] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_files', 'setup_http_conn', 'manual__2022-07-16T19:05:47.374925+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/process_files.py', '--cfg-path', '/tmp/tmpmjwi4xuf', '--error-file', '/tmp/tmpluks3sl1']
[2022-07-16 19:12:52,015] {standard_task_runner.py:80} INFO - Job 8: Subtask setup_http_conn
[2022-07-16 19:12:52,062] {task_command.py:371} INFO - Running <TaskInstance: process_files.setup_http_conn manual__2022-07-16T19:05:47.374925+00:00 [running]> on host 98d7be6daedb
[2022-07-16 19:12:52,123] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_files
AIRFLOW_CTX_TASK_ID=setup_http_conn
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T19:05:47.374925+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T19:05:47.374925+00:00
[2022-07-16 19:12:52,124] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-16 19:12:52,124] {subprocess.py:74} INFO - Running command: ['bash', '-c', "\n*** connections add -a 'http_api'     --conn-type 'http'     --conn-host 'raw.githubusercontent.com/tadinve/EKG-Foundations/master/04A-postgress/' "]
[2022-07-16 19:12:52,137] {subprocess.py:85} INFO - Output:
[2022-07-16 19:12:52,838] {subprocess.py:92} INFO - 
[2022-07-16 19:12:52,838] {subprocess.py:92} INFO - *** command error: unrecognized arguments: -a, see help above.
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO - usage: *** [-h] GROUP_OR_COMMAND ...
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO - 
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO - positional arguments:
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -   GROUP_OR_COMMAND
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO - 
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -     Groups:
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       celery         Celery components
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       config         View configuration
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       connections    Manage connections
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       dags           Manage DAGs
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       db             Database operations
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       jobs           Manage jobs
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       kubernetes     Tools to help run the KubernetesExecutor
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       pools          Manage pools
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       providers      Display providers
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       roles          Manage roles
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       tasks          Manage tasks
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       users          Manage users
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       variables      Manage variables
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO - 
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -     Commands:
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       cheat-sheet    Display cheat sheet
[2022-07-16 19:12:52,839] {subprocess.py:92} INFO -       dag-processor  Start a standalone Dag Processor instance
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       info           Show information about current Airflow and environment
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       kerberos       Start a kerberos ticket renewer
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       plugins        Dump information about loaded plugins
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       rotate-fernet-key
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -                      Rotate encrypted connection credentials and variables
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       scheduler      Start a scheduler instance
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       standalone     Run an all-in-one copy of Airflow
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       sync-perm      Update permissions for existing roles and optionally DAGs
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       triggerer      Start a triggerer instance
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       version        Show the version
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -       webserver      Start a Airflow webserver instance
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO - 
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO - optional arguments:
[2022-07-16 19:12:52,840] {subprocess.py:92} INFO -   -h, --help         show this help message and exit
[2022-07-16 19:12:52,887] {subprocess.py:96} INFO - Command exited with return code 2
[2022-07-16 19:12:52,902] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-07-16 19:12:52,905] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=process_files, task_id=setup_http_conn, execution_date=20220716T190547, start_date=20220716T191251, end_date=20220716T191252
[2022-07-16 19:12:52,914] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task setup_http_conn (Bash command failed. The command returned a non-zero exit code 2.; 1474)
[2022-07-16 19:12:52,948] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 19:12:52,990] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
